language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install --use-mirrors tox
  - pip install --use-mirrors coveralls
script: TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | tr -d .) tox
after_success:
  coveralls
